### ISSUE TITLE
[BUG] Download broken on Windows

### ISSUE THREAD

**Issue by evertiro** [arnohovhannisyan/vscode-syncify#16]
### Syncify Version

2.0.0+

### Describe the bug

I use Syncify on both Linux and Windows. On my Linux systems, it works fine. On Windows, the download option has been broken since release 2.0.0.

### Additional context

The following error is displayed on newer versions:

```
TypeError: downloadedExtensions.filter is not a function	
at Function.getMissing (file:////home/travis/build/arnohovhannisyan/vscode-syncify/src/services/extensions.ts:54:37)	
at RepoSyncer.eval (file:////home/travis/build/arnohovhannisyan/vscode-syncify/src/syncers/repo.ts:176:82)	
at Generator.next (<anonymous>)	at fulfilled (file:////home/travis/build/arnohovhannisyan/vscode-syncify/src/syncers/repo.ts:5:58) (at Function.error (file:////home/travis/build/arnohovhannisyan/vscode-syncify/src/services/logger.ts:8:21))
```

**Comment by arnohovhannisyan** [comment]
@evertiro Please install the [this](https://cdn.discordapp.com/attachments/632780237637287966/632780273892982814/syncify-2.1.3.vsix), try downloading, and reply with everything in the console.

Tutorial: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by evertiro** [comment]
```
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.log.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/log/syntaxes/log.tmLanguage.json.
New grammar file: file:///c%3A/Users/Evertiro/.vscode-insiders/extensions/emilast.logfilehighlighter-2.6.0/syntaxes/log.tmLanguage
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///c%3A/Users/Evertiro/.vscode-insiders/extensions/redhat.vscode-yaml-0.5.3/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host] MonokaiPro-VSCode 1.1.14, ©2019 Monokai  (at new e (c:\Users\Evertiro\.vscode-insiders\extensions\monokai.theme-monokai-pro-vscode-1.1.14\js\app.js:10:16036))
console.ts:137 [Extension Host] Looking for parseable documents... (at c:\Users\Evertiro\.vscode-insiders\extensions\gencer.html-slim-scss-css-class-completion-1.5.20\src\extension.ts:57:17)
console.ts:137 [Extension Host] vscode pigments is activated (at activate (c:\Users\Evertiro\.vscode-insiders\extensions\jaspernorth.vscode-pigments-2.0.0\out\extension.js:61:13))
console.ts:137 [Extension Host] [VSCodeCounter] now active! (at activate (c:\Users\Evertiro\.vscode-insiders\extensions\uctakeoff.vscode-counter-1.2.1\out\extension.js:30:13))
console.ts:137 [Extension Host] Found no documents (at c:\Users\Evertiro\.vscode-insiders\extensions\gencer.html-slim-scss-css-class-completion-1.5.20\src\extension.ts:67:21)
console.ts:137 [Extension Host]% Object__proto__: Object (at RepoSyncer.eval (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/syncers/repo.ts:176:29))
console.ts:137 [Extension Host] TypeError: downloadedExtensions.filter is not a function    at Function.getMissing (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/services/extensions.ts:54:37)    at RepoSyncer.eval (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/syncers/repo.ts:177:82)    at Generator.next (<anonymous>)    at fulfilled (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/syncers/repo.ts:5:58) (at Function.error (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/services/logger.ts:8:21))
t.log @ console.ts:137
notificationsAlerts.ts:40 Syncify: Please check the Developer Console for specific error (Help -> Toggle Developer Tools)
onDidNotificationChange @ notificationsAlerts.ts:40
extensionHost.ts:201 Extension Host
extensionHost.ts:202 Debugger attached.
```

**Comment by arnohovhannisyan** [comment]
@evertiro Can you try [this version](https://cdn.discordapp.com/attachments/632780237637287966/632787454457282570/syncify-2.1.3.vsix)? Let me know if the issue is still happening.

**Comment by evertiro** [comment]
```
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.log.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/log/syntaxes/log.tmLanguage.json.
New grammar file: file:///c%3A/Users/Evertiro/.vscode-insiders/extensions/emilast.logfilehighlighter-2.6.0/syntaxes/log.tmLanguage
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///c%3A/Users/Evertiro/.vscode-insiders/extensions/redhat.vscode-yaml-0.5.3/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host] MonokaiPro-VSCode 1.1.14, ©2019 Monokai  (at new e (c:\Users\Evertiro\.vscode-insiders\extensions\monokai.theme-monokai-pro-vscode-1.1.14\js\app.js:10:16036))
console.ts:137 [Extension Host] Looking for parseable documents... (at c:\Users\Evertiro\.vscode-insiders\extensions\gencer.html-slim-scss-css-class-completion-1.5.20\src\extension.ts:57:17)
console.ts:137 [Extension Host] vscode pigments is activated (at activate (c:\Users\Evertiro\.vscode-insiders\extensions\jaspernorth.vscode-pigments-2.0.0\out\extension.js:61:13))
console.ts:137 [Extension Host] [VSCodeCounter] now active! (at activate (c:\Users\Evertiro\.vscode-insiders\extensions\uctakeoff.vscode-counter-1.2.1\out\extension.js:30:13))
console.ts:137 [Extension Host] Found no documents (at c:\Users\Evertiro\.vscode-insiders\extensions\gencer.html-slim-scss-css-class-completion-1.5.20\src\extension.ts:67:21)
console.ts:137 [Extension Host] Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\git_service.js:5:69)
    at fetch (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\git_service.js:11:10)
    at fetchRemoteUrl (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\git_service.js:114:28) (at Object.fetchCurrentPipelineProject (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\gitlab_service.js:120:13))
console.ts:137 [Extension Host] Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\git_service.js:5:69)
    at fetch (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\git_service.js:11:10)
    at fetchRemoteUrl (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\git_service.js:114:28) (at Object.fetchCurrentProject (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\gitlab_service.js:108:13))
console.ts:137 [Extension Host] Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\git_service.js:5:69)
    at fetch (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\git_service.js:11:10)
    at fetchRemoteUrl (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\git_service.js:114:28) (at fetchCurrentPipelineProject (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\gitlab_service.js:120:13))
console.ts:137 [Extension Host] Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\git_service.js:5:69)
    at fetch (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\git_service.js:11:10)
    at fetchRemoteUrl (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\git_service.js:114:28) (at fetchCurrentProject (c:\Users\Evertiro\.vscode-insiders\extensions\fatihacet.gitlab-workflow-2.1.1\src\gitlab_service.js:108:13))
console.ts:137 [Extension Host] SyntaxError: Unexpected end of JSON input    at JSON.parse (<anonymous>)    at Function.processIncoming (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/services/pragma.ts:61:18)    at RepoSyncer.eval (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/syncers/repo.ts:278:59)    at Generator.next (<anonymous>)    at fulfilled (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/syncers/repo.ts:5:58) (at Function.error (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/services/logger.ts:8:21))
t.log @ console.ts:137
notificationsAlerts.ts:40 Syncify: Please check the Developer Console for specific error (Help -> Toggle Developer Tools)
onDidNotificationChange @ notificationsAlerts.ts:40
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: command 'syncify.cancelUpload' already exists (at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:789:521)
t.log @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: command 'syncify.cancelUpload' already exists    at v.registerCommand (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:519:448)    at Object.registerCommand (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:693:699)    at Function.eval (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/services/watcher.ts:49:50)    at Generator.next (<anonymous>)    at fulfilled (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/services/watcher.ts:5:58) (at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:789:597)
t.log @ console.ts:137
log.ts:196   ERR command 'syncify.cancelUpload' already exists: Error: command 'syncify.cancelUpload' already exists
    at v.registerCommand (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:519:448)
    at Object.registerCommand (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:693:699)
    at Function.eval (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/services/watcher.ts:49:50)
    at Generator.next (<anonymous>)
    at fulfilled (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/services/watcher.ts:5:58)
console.ts:137 [Extension Host] SyntaxError: Unexpected end of JSON input    at JSON.parse (<anonymous>)    at Function.processIncoming (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/services/pragma.ts:61:18)    at RepoSyncer.eval (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/syncers/repo.ts:278:59)    at Generator.next (<anonymous>)    at fulfilled (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/syncers/repo.ts:5:58) (at Function.error (file:////run/media/arno/Files/Projects/Programming/vscode-syncify/src/services/logger.ts:8:21))
t.log @ console.ts:137
notificationsAlerts.ts:40 Syncify: Please check the Developer Console for specific error (Help -> Toggle Developer Tools)
onDidNotificationChange @ notificationsAlerts.ts:40
```

**Comment by arnohovhannisyan** [comment]
@evertiro [New vsix](https://cdn.discordapp.com/attachments/632780237637287966/632790556220719114/syncify-2.1.3.vsix). Please reply with everything in the console that is between the `START --` and `-- END`.

**Comment by evertiro** [comment]
Looks like that's just the JSON for the settings file... 

```
{
  "alignment.operatorPadding": "left",
  "code-runner.clearPreviousOutput": true,
  "code-runner.runInTerminal": true,
  "code-runner.saveFileBeforeRun": true,
  "codestream.email": "xxx",
  "csharp.referencesCodeLens.enabled": false,
  "css.validate": false,
  "editor.rulers": [80],
  "git.autofetch": true,
  "git.confirmSync": false,
  "git.ignoreLegacyWarning": true,
  "gitlabPipelineMonitor": {
    "gitlab.com": { "token": "xxx", "notifyOnFailed": true }
  },
  "gitlens.showWhatsNewAfterUpgrades": false,
  "jshint.lintHTML": true,
  "less.validate": false,
  "minify.minifyExistingOnSave": true,
  "papyrus.fo4.directory": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Skyrim Special Edition\\",
  "remote.SSH.showLoginTerminal": true,
  "restructuredtext.linter.executablePath": "/usr/local/bin/doc8",
  "restructuredtext.linter.extraArgs": ["--ignore D001"],
  "restructuredtext.sphinxBuildPath": "/usr/bin/sphinx-build",
  "scss.validate": false,
  "showGitMetrics": false,
  "showMusicMetrics": false,
  "showWeeklyRanking": false,
  "svn.enableProposedApi": "none",
  "sync.askGistName": true,
  "sync.autoDownload": true,
  "sync.autoUpload": true,
  "sync.gist": "xxx",
  "terminal.external.linuxExec": "zsh",
  "terminal.integrated.shell.linux": "/bin/zsh",
  "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
  "window.titleBarStyle": "custom",
  "window.zoomLevel": 0,
  "workbench.colorTheme": "One Monokai",
  "workbench.iconTheme": "Monokai Pro Icons",
  "workbench.startupEditor": "newUntitledFile",
  "editor.fontFamily": "'Fira Mono', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
  "editor.autoClosingOvertype": "always",
  "zenMode.hideLineNumbers": false,
  "zenMode.hideStatusBar": false,
  "window.title": "${dirty}${activeEditorMedium}${separator}${rootName}",
  "explorer.incrementalNaming": "smart",
  "gitlab.enableExperimentalFeatures": true,
  "gitlab.ignoreCertificateErrors": true,
  "gitlab.showPipelineUpdateNotifications": true,
  "prettier.singleQuote": true
}
```

**Comment by arnohovhannisyan** [comment]
Did any errors occur?

**Comment by evertiro** [comment]
Yes. Effectively the same as my previous post

**Comment by arnohovhannisyan** [comment]
@evertiro If it's all right, can you please follow these steps?

1. Run `Syncify: Reset` in the command palette and confirm
2. Reload VSCode
3. Set up the extension
4. Download

I have tested this on my Windows machine and don't get this error, so it might be specific to your machine.

**Comment by arnohovhannisyan** [comment]
@evertiro Are there any updates on this issue?

**Comment by evertiro** [comment]
It was working for a while (after doing the reset), just reinstalled Windows for an unrelated reason, reinstalled and now it's throwing a JSON error whenever I try to connect. Interestingly, the new GitLab integration fails on callback.

**Comment by arnohovhannisyan** [comment]
@evertiro 

> Interestingly, the new GitLab integration fails on callback.

Can you make a new issue and post the error on there?

> it's throwing a JSON error whenever I try to connect

Please take a screenshot of the error in the console and reply with it.

**Comment by evertiro** [comment]
Oddly, after updating to 1.40.0 the GitLab integration is working now. Testing whether or not that fixed sync as well.

**Comment by evertiro** [comment]
Here's the entirety of the console error log:

```workbench.desktop.main.js:sourcemap:4267 Overwriting grammar scope name to file mapping for scope documentation.injection.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/typescript-basics/syntaxes/jsdoc.ts.injection.tmLanguage.json.
New grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/typescript-basics/syntaxes/jsdoc.js.injection.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:4267
workbench.desktop.main.js:sourcemap:4267 Overwriting grammar scope name to file mapping for scope text.log.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/log/syntaxes/log.tmLanguage.json.
New grammar file: file:///c%3A/Users/Evertiro/.vscode-insiders/extensions/emilast.logfilehighlighter-2.6.0/syntaxes/log.tmLanguage
register @ workbench.desktop.main.js:sourcemap:4267
workbench.desktop.main.js:sourcemap:250 [Extension Host] MonokaiPro-VSCode 1.1.14, ©2019 Monokai  (at new e (c:\Users\Evertiro\.vscode-insiders\extensions\monokai.theme-monokai-pro-vscode-1.1.14\js\app.js:10:16036))
workbench.desktop.main.js:sourcemap:250 [Extension Host] SyntaxError: Unexpected end of JSON input	at JSON.parse (<anonymous>)	at Function.processIncoming (file:////home/travis/build/arnohovhannisyan/vscode-syncify/src/services/pragma.ts:61:18)	at RepoSyncer.eval (file:////home/travis/build/arnohovhannisyan/vscode-syncify/src/syncers/repo.ts:293:63)	at Generator.next (<anonymous>)	at fulfilled (file:////home/travis/build/arnohovhannisyan/vscode-syncify/src/syncers/repo.ts:5:58) (at Function.error (file:////home/travis/build/arnohovhannisyan/vscode-syncify/src/services/logger.ts:6:17))
t.log @ workbench.desktop.main.js:sourcemap:250
```

Here's what I'm seeing in app...

![2019-10-29 14_37_27](https://user-images.githubusercontent.com/36433/67802852-ef940780-fa59-11e9-9194-66ec002686a0.png)

**Comment by arnohovhannisyan** [comment]
@evertiro Can you check your repository to make sure that `keybindings.json` is not empty? If it is, please edit it and just add `[]`.

**Comment by evertiro** [comment]
Aha, it is empty. That's an annoying quirk, especially since Syncify is what uploaded it

**Comment by arnohovhannisyan** [comment]
Yeah, I plan on releasing a new version soon that checks for valid JSON before parsing it.
